[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -Dspring.profiles.active=prod -jar target/PROJECT_GRP-10-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
SPRING_PROFILES_ACTIVE = "prod"